version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                  name: "Pull Submodules"
                  command: git submodule update --init --recursive --depth=1
            - run: docker build -f .circleci/Dockerfile.test .
